#This is an example of the "Not a chicken" non-simplified gesture.

#THIS GESTURE WILL NOT WORK FOR YOU UNLESS YOUR SERVO SERVICES MATCH THE SAME NAMES AS MINE! That or your change the names of my setup to match yours. :9 

#NOTE .setSpeed(-1) which is used in this gesture is now deprecated. If you are using myrobotlab-1.1.1393 or above, please use ".setMaxSpeed()" as it is the newest setting to return servos to their full speed / remove speed limits. 

###############################################################################

sleep(2) #2second buffer so that the gesture starts 2 seconds after you execute it. Can be removed. 

Neck.moveTo(160) #THAT IS NOT A CHICKEN INTRO
NeckRoll.moveTo(90)
LeftOuterEyebrow.moveTo(180)
LeftInnerEyebrow.moveTo(180)
RightOuterEyebrow.moveTo(180)
RightInnerEyebrow.moveTo(180)
LeftEyeUD.moveTo(70)
RightEyeUD.moveTo(70)
LeftEyeLR.moveTo(90)
RightEyeLR.moveTo(90)
sleep(0.4)

Neck.moveTo(154)
sleep(0.4)

LeftEyelidUpper.moveTo(0)
LeftEyelidLower.moveTo(0)
RightEyelidUpper.moveTo(0)
RightEyelidLower.moveTo(0)
sleep(0.07)

LeftEyelidUpper.moveTo(180)
LeftEyelidLower.moveTo(180)
RightEyelidUpper.moveTo(180)
RightEyelidLower.moveTo(180)
sleep(0.6)

LeftOuterEyebrow.moveTo(110)
LeftInnerEyebrow.moveTo(180)
RightOuterEyebrow.moveTo(0)
RightInnerEyebrow.moveTo(0)
NeckRoll.moveTo(140)
LateralJaw.moveTo(120)
sleep(0.8)

LateralJaw.moveTo(90)
LeftEyelidUpper.moveTo(0)
LeftEyelidLower.moveTo(0)
RightEyelidUpper.moveTo(0)
RightEyelidLower.moveTo(0)
sleep(0.07)

LeftEyelidUpper.moveTo(180)
LeftEyelidLower.moveTo(180)
RightEyelidUpper.moveTo(180)
RightEyelidLower.moveTo(180)
sleep(0.4)

Neck.moveTo(90) #THAT IS NOT A CHICKEN START
NeckRoll.moveTo(90)
LeftEyeUD.moveTo(90)
RightEyeUD.moveTo(90)
LeftEyeLR.moveTo(90)
RightEyeLR.moveTo(90)
LeftEyelidUpper.moveTo(180)
LeftEyelidLower.moveTo(180)
RightEyelidUpper.moveTo(180)
RightEyelidLower.moveTo(180)
LeftOuterEyebrow.moveTo(90)
LeftInnerEyebrow.moveTo(90)
RightOuterEyebrow.moveTo(90)
RightInnerEyebrow.moveTo(90)
NeckRot.setSpeed(30)
NeckRot.moveTo(110)
StomTop.moveTo(140)
StomMid.moveTo(20)
RightArmBicep.moveTo(150)
RightArmRotate.moveTo(100)
RightArmShoulder.moveTo(95)
RightArmOmoplate.moveTo(45)
sleep(0.5)

NeckRoll.moveTo(25)
LeftOuterEyebrow.setSpeed(50)
LeftInnerEyebrow.setSpeed(50)
RightOuterEyebrow.setSpeed(50)
RightInnerEyebrow.setSpeed(50)
LeftOuterEyebrow.moveTo(150)
LeftInnerEyebrow.moveTo(0)
RightOuterEyebrow.moveTo(150)
RightInnerEyebrow.moveTo(0)
LeftEyelidUpper.setSpeed(50)
LeftEyelidLower.setSpeed(50)
RightEyelidUpper.setSpeed(50)
RightEyelidLower.setSpeed(50)
LeftEyelidUpper.moveTo(30)
LeftEyelidLower.moveTo(30)
RightEyelidUpper.moveTo(30)
RightEyelidLower.moveTo(30)
mouth.audioFile.play('C:\MRL\CustomMovement\Audio\ThatIsNOTaChicken.mp3')  #This line will pull an error if you don't have a matching soundfile "ThatIsNOTaChicken.mp3" in a folder you have it directed it to.
sleep(0.7)

LeftArmBicep.moveTo(130) #BEGINNING OF LEFT ARM MOVEMENT
LeftArmRotate.moveTo(60)
LeftArmOmoplate.moveTo(20)
LeftArmShoulder.moveTo(70)
RightHandThumb.moveTo(180)
RightHandIndex.moveTo(0)
RightHandMiddle.moveTo(180)
RightHandRing.moveTo(180)
RightHandPinky.moveTo(180)
RightHandWrist.moveTo(180)
sleep(1)

LeftHandWrist.moveTo(130)
LeftHandThumb.moveTo(140)
LeftHandIndex.moveTo(180)
LeftHandMiddle.moveTo(180)
LeftHandRing.moveTo(180)
LeftHandPinky.moveTo(180)
LeftEyelidUpper.setSpeed(200)
LeftEyelidLower.setSpeed(200)
RightEyelidUpper.setSpeed(200)
RightEyelidLower.setSpeed(200)
LeftEyelidUpper.moveTo(0)
LeftEyelidLower.moveTo(0)
RightEyelidUpper.moveTo(0)
RightEyelidLower.moveTo(0)
sleep(0.07)

LeftEyelidUpper.moveTo(50)
LeftEyelidLower.moveTo(50)
RightEyelidUpper.moveTo(50)
RightEyelidLower.moveTo(50)
RightArmRotate.moveTo(100)
RightArmOmoplate.moveTo(35)
sleep(0.9)

RightArmBicep.moveTo(70)
RightArmShoulder.moveTo(75)
sleep(0.5)

LeftEyelidUpper.setSpeed(200)
LeftEyelidLower.setSpeed(200)
RightEyelidUpper.setSpeed(200)
RightEyelidLower.setSpeed(200)
LeftEyelidUpper.moveTo(0)
LeftEyelidLower.moveTo(0)
RightEyelidUpper.moveTo(0)
RightEyelidLower.moveTo(0)
sleep(0.07)

LeftEyelidUpper.moveTo(180)
LeftEyelidLower.moveTo(180)
RightEyelidUpper.moveTo(180)
RightEyelidLower.moveTo(180)
RightArmBicep.moveTo(130)
sleep(1)

LeftOuterEyebrow.moveTo(180)
LeftInnerEyebrow.moveTo(180)
RightOuterEyebrow.moveTo(90)
RightInnerEyebrow.moveTo(90)
StomTop.moveTo(100)
StomMid.moveTo(110)
LeftArmBicep.moveTo(5)
LeftArmRotate.moveTo(90)
LeftArmShoulder.moveTo(40)
LeftArmOmoplate.moveTo(5)
sleep(0.1)

NeckRot.moveTo(88)
sleep(0.1)

RightArmRotate.moveTo(75)
RightArmOmoplate.moveTo(60)
sleep(0.6)

########END OF NOT A CHICKEN / RETURN TO REST / RESET SPEEDS#############
Neck.moveTo(90)
NeckRoll.moveTo(90)
NeckRot.setSpeed(140)
NeckRot.moveTo(90)

StomTop.moveTo(90)
StomMid.moveTo(90)

LeftEyelidUpper.setSpeed(-1) 
LeftEyelidLower.setSpeed(-1)
RightEyelidUpper.setSpeed(-1)
RightEyelidLower.setSpeed(-1)
LeftEyelidUpper.moveTo(180)
LeftEyelidLower.moveTo(180)
RightEyelidUpper.moveTo(180)
RightEyelidLower.moveTo(180)

LeftOuterEyebrow.setSpeed(-1)
LeftInnerEyebrow.setSpeed(-1)
RightOuterEyebrow.setSpeed(-1)
RightInnerEyebrow.setSpeed(-1)
LeftOuterEyebrow.moveTo(90)
LeftInnerEyebrow.moveTo(90)
RightOuterEyebrow.moveTo(90)
RightInnerEyebrow.moveTo(90)

LeftEyeUD.moveTo(90)
RightEyeUD.moveTo(90)
LeftEyeLR.moveTo(90)
RightEyeLR.moveTo(90)

LateralJaw.moveTo(90)

LeftArmBicep.moveTo(5)
LeftArmRotate.moveTo(90)
LeftArmShoulder.moveTo(40)
LeftArmOmoplate.moveTo(5)
LeftHandThumb.moveTo(0)
LeftHandIndex.moveTo(0)
LeftHandMiddle.moveTo(0)
LeftHandRing.moveTo(0)
LeftHandPinky.moveTo(0)
LeftHandWrist.moveTo(0)

RightArmBicep.moveTo(5)
RightArmRotate.moveTo(90)
RightArmShoulder.moveTo(40)
RightArmOmoplate.moveTo(5)
RightHandThumb.moveTo(0)
RightHandIndex.moveTo(0)
RightHandMiddle.moveTo(0)
RightHandRing.moveTo(0)
RightHandPinky.moveTo(0)
RightHandWrist.moveTo(180)
